### ISSUE TITLE
ROI activity tracker improvements

### ISSUE THREAD

**Issue by Giulia2906** [thladnik/vxPy#33]
1. Set a threshold for each ROI individually
2. Save ROI activity traces in camera file
3. Color or text label for each ROI within the Ca image (so that you can match the ROI with the activity trace)

**Comment by thladnik** [comment]
Features added with commits e7e7e18e293acc865672bf4081479f0751420dcc and 825ef2de25a06d23530cbd7be18cd4855f75d5a4
